Create config
gecraft/bsa pull request #14
Opened 2021-02-23 10:18 UTC by Valyukhov

2021-02-23 10:55 UTC, foxprogs requested changes

2021-02-23 10:55 UTC, foxprogs commented on src/components/BookList/BookList.js
> +            <falsebutton>{mainResourse.title}</falsebutton>
Браузер ругается что такого тега нет. Может заменить на span и например добавить className="falsebutton"

2021-02-23 10:55 UTC, foxprogs commented on src/components/BookList/styled.js
> +  falsebutton {
и тут тогда заменить на класс .falsebutton

2021-02-24 13:42 UTC, foxprogs approved these changes

2021-02-24 14:28 UTC, Valyukhov commented
1. Add config,js (include list and property of books).
2. Parse translation and compare with config.js. 
3. If there is no books in the translation - the link to the books is not available.
4. Add checkbox: when checked - the inactive links become invisible.

2021-02-25 13:27 UTC, closed without merging

2021-02-25 13:28 UTC, Valyukhov commented
Too much conflicts. Re-branch from develop to feature-AlexVal-addHideFalseBooks