Typo report
gecraft/bsa pull request #21
Opened 2021-03-13 06:25 UTC by dimanya

final

2021-03-14 11:56 UTC, Valyukhov reviewed
В целом - отлично сделано, кода совсем немного для такого серьезного компонента. Но я бы добавил красную кнопку 'Cancel'. Юзер мог просто перепутать  и выделил по ошибке другой текст, да и просто передумать.  
Конфликты при мердже нужно исправлять

2021-03-14 11:56 UTC, Valyukhov commented on src/components/TypoReport/index.js
>        .catch((error) => console.log(error));
В консоле при рендере модального окна выскакивает waypoint hit и warning (Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: )

2021-03-14 17:31 UTC, foxprogs requested changes

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/index.js
> +  const [openbackdrop, setOpenbackdrop] = React.useState(false);
need use camelCase (openBackdrop)

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/index.js
> +  const [open, setOpen] = React.useState(false);
Можешь тогда дать понятное имя, по аналогии с бэкдроп

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/index.js
> +export default function BottomAppBar() {
export default function TypoReport

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/style.js
> +  appBar: {
add please padding: "10px" and we need to fix the main layout because this bar overlaps with content.

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/index.js
> +      <Container fixed>
Свойство fixed тут точно нужно?

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/index.js
>        .catch((error) => console.log(error));
@Valyukhov  да, с этим ворнингом пока проблема, не ясно как решить. В доках написано использовать ref. Может потом исправим, на работу не влияет)

2021-03-14 17:31 UTC, foxprogs commented on src/components/TypoReport/index.js
> +              </Button>
Согласен с @Valyukhov тут можно было бы добавить кнопку отмены например. Или сделать крестик и модалки.

2021-03-15 07:06 UTC, foxprogs approved these changes

2021-03-15 10:27 UTC, Vorobushec approved these changes

2021-03-15 10:32 UTC, merged