Change design with MUI style
gecraft/bsa pull request #7
Opened 2021-01-30 17:02 UTC by Valyukhov

2021-01-30 20:27 UTC, Vorobushec requested changes

2021-01-30 20:27 UTC, Vorobushec commented on src/components/MenuBar.js
> +console.log(AppBar);
Я думаю, здесь нужно убрать console.log

2021-01-31 11:34 UTC, foxprogs commented on src/components/MenuBar.js
> +            </Typography>
Лучше тут использовать forEach или map для обхода массива а не обращаться к элементам на прямую по индексу

2021-01-31 11:47 UTC, Valyukhov commented on src/components/MenuBar.js
> +            </Typography>
Ты знаешь, я когда начал засовывать менюшку в массив так и хотел сделать. Но потом понял, что в дальнейшем на элементы нужно будет линки разные кидать и по идее нужно или вручную в теги или обьектом со свойством ссылка. Но показалось слишком замудрённо и оставил такое половинчатое решение. Посоветуй как лучше.

2021-01-31 11:47 UTC, Valyukhov commented on src/components/MenuBar.js
> +console.log(AppBar);
Да, точно. Я убирал, но похоже не тот коммит отправил. Спасибо, Тимур, изменю.

2021-01-31 13:24 UTC, foxprogs commented on src/components/MenuBar.js
> +            </Typography>
Я бы сделал пока что массив объектов. У нас еще этих страниц нет так что пусть будет что-нибудь типа [{title:"Заголовок1"}, {title:"Заголовок2"}] а уже потом по мере продвижения будем добавлять ссылки.

2021-01-31 18:12 UTC, foxprogs commented on src/components/MenuBar.js
> +      {' '}
какой-то пустой блок попал тут

2021-01-31 18:13 UTC, foxprogs commented on src/components/MenuBar.js
> +        }}
и у тебя везде классы используются, можно этот инлайн стиль тоже перенести в класс.

2021-01-31 18:46 UTC, Vorobushec approved these changes

2021-02-01 17:31 UTC, Serge-Ntumba commented
Нормально только есть место ты используешь "" а другие '' поидет но не очень хорошо

2021-02-01 18:06 UTC, Serge-Ntumba commented
Я думаю, все нормально

2021-02-02 07:28 UTC, merged